spring:
  application:
    name: demo-consumer
server:
  port: 8662

eureka:
  client:
    service-url:
      defaultZone: http://root:abcd4321@10.10.171.244:8761/eureka/,http://root:abcd4321@10.10.171.245:8761/eureka/,http://root:abcd4321@10.10.171.246:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}