spring:
  application:
    name: demo-eureka
  security:
    user:
      name: root
      password: abcd4321
      roles: SERVICE_NODE
server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://10.10.171.244:8761/eureka/,http://10.10.171.245:8761/eureka/,http://10.10.171.246:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: node244