spring:
  application:
    name: demo-eureka
  security:
    user:
      name: root
      password: abcd4321
      roles: SERVICE_NODE
server:
  port: 8671

eureka:
  client:
    service-url:
      defaultZone: http://root:abcd4321@10.10.171.244:8671/eureka/,http://root:abcd4321@10.10.171.245:8671/eureka/,http://root:abcd4321@10.10.171.246:8671/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: local-eureka-czm
