spring:
  application:
    name: security
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8681
  shutdown: graceful
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'