server:
  port: 8670

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Harpagonming/SpringCloud.git
          search-paths: configuration
          basedir: ./temp
  application:
    name: config-server