spring:
  application:
    name: eureka-node2
  security:
    user:
      name: root
      password: abcd4321
      roles: SERVICE_NODE
server:
  port: 8672

eureka:
  client:
    service-url:
      defaultZone: http://root:abcd4321@127.0.0.1:8671/eureka/,http://root:abcd4321@127.0.0.1:8672/eureka/,http://root:abcd4321@127.0.0.1:8673/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: local-${spring.application.name}