spring:
  application:
    name: eureka-node3
server:
  port: 8673

eureka:
  client:
    service-url:
      defaultZone: http://root:abcd4321@127.0.0.1:8671/eureka/,http://root:abcd4321@127.0.0.1:8672/eureka/,http://root:abcd4321@127.0.0.1:8673/eureka/
  instance:
    instance-id: local-${spring.application.name}