spring:
  application:
    name: eureka
#  security:
#    user:
#      name: root
#      password: abcd4321
#      roles: SERVICE_NODE
server:
  port: 8671

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    instance-id: local-eureka
