spring:
  application:
    name: gateway-zookeeper
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: 10.10.171.244:2181,10.10.171.245:2181,10.10.171.246:2181
server:
  port: 8674