spring:
  cloud:
    config:
      uri: http://127.0.0.1:8670
    zookeeper:
      discovery:
        instance-port: ${server.port}
        enabled: true
        register: true
        instance-host: ${spring.cloud.client.ipAddress}
      connect-string: 10.10.171.244:2181,10.10.171.245:2181,10.10.171.246:2181